### ISSUE TITLE
Getting 'Missing region in config' when running gulp

### ISSUE THREAD

**Issue by lgrosales** [binoculars/aws-cloudformation-cognito-identity-pool#1]
Hi, I'm getting 'Missing region in config' when running gulp. The region is properly configured in my ~/.aws/config file but it seems that is not being picked up.
I had to explicitly set the region before creating any AWS resource to make it work.

**Comment by binoculars** [comment]
This is actually a problem with the AWS SDK and not this repo itself.

You'll have to add this to your shell's init script (`~/.bash_profile`, `~/.zshrc`):
For example: `export AWS_REGION="us-east-1"`

Keep in mind that this is only necessary locally and in the Lambda environment, it will get the region from `process.env.AWS_REGION`
